include: package:very_good_analysis/analysis_options.2.4.0.yaml
analyzer:
  exclude: [build/**, lib/**.freezed.dart, lib/**.g.dart, secrets/*]
linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    avoid_print: false
    flutter_style_todos: false
