name: flutterbase
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  firebase_auth: ^4.2.8
  firebase_core: ^2.6.1
  firebase_core_web: ^2.2.1
  firebase_ui_auth: ^1.1.13
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.1.1
  intl: ^0.17.0
  riverpod: ^2.2.0

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
