name: listwhatever
description: A starter template for Flutter projects
version: 0.0.46+0000001
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  android_intent_plus: ^5.1.0
  another_xlider: ^3.0.2
  autocomplete_textfield: ^2.0.1
  bloc: ^8.1.4
  bloc_concurrency: ^0.2.2
  cloud_firestore: ^5.5.1
  collection: ^1.18.0
  csv: ^6.0.0
  device_info_plus: ^11.2.0
  equatable: ^2.0.3
  firebase_analytics: ^11.2.1
  firebase_auth: ^5.3.4
  firebase_auth_platform_interface: ^7.4.3
  firebase_core: ^3.8.1
  
  firebase_core_platform_interface: ^5.2.0
  firebase_crashlytics: ^4.0.4
  firebase_in_app_messaging: ^0.8.0+4 
  firebase_messaging: ^15.0.4
  firebase_performance: ^0.10.0+4
  firebase_remote_config: ^5.0.4
  firebase_storage: ^12.1.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_form_builder: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_map: ^7.0.2
  flutter_map_cancellable_tile_provider: ^3.0.0
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.5
  flutter_typeahead: ^5.2.0
  font_awesome_flutter: ^10.1.0
  form_builder_extra_fields: ^11.0.0
  form_builder_image_picker: ^4.1.0
  form_builder_validators: ^11.0.0
  formz: ^0.7.0
  freezed_annotation: ^2.4.4
  geolocator: ^13.0.1
  go_router: ^14.6.2
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.5.0
  google_maps_flutter_web: ^0.5.4+2
  google_mobile_ads: ^5.1.0
  google_sign_in: ^6.2.2
  google_sign_in_web: ^0.12.0+4
  great_circle_distance_calculator: ^1.0.4
  http: ^1.0.0
  hugeicons: ^0.0.7
  hydrated_bloc: ^9.1.2
  image_picker: ^1.0.7
  intl: ^0.19.0
  json_annotation: ^4.9.0
  latlong2: ^0.9.0
  logger: ^2.0.2+1
  meta: ^1.15.0
  path_provider: ^2.1.1
  permission_handler: ^11.3.1
  platform: ^3.0.2
  plugin_platform_interface: ^2.1.7
  pluto_grid: ^8.0.0
  share_plus: ^10.0.0
  share_plus_platform_interface: ^5.0.0
  shared_preferences: ^2.2.1
  sign_in_with_apple: ^6.1.4
  url_launcher: ^6.1.5

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.13
  build_verify: ^3.1.0
  flutter_gen_runner: ^5.7.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  integration_test:
    sdk: flutter
  json_serializable: ^6.9.0
  mocktail: ^1.0.4
  test: ^1.25.7
  url_launcher_platform_interface: ^2.2.0
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
