name: listanything
description: List anything, sometimes with a map
version: 0.0.16+0000001
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  another_xlider: ^3.0.1
  cloud_firestore: ^4.4.3
  device_info_plus: ^8.1.0
  firebase_auth: ^4.2.8
  firebase_core: ^2.6.1
  firebase_core_web: ^2.2.1
  firebase_ui_auth: ^1.1.13
  firebase_ui_oauth_google: ^1.0.21
  flutter:
    sdk: flutter
  flutter_form_builder: ^7.7.0
  flutter_hooks: ^0.18.6
  flutter_localizations:
    sdk: flutter
  flutter_map: ^3.1.0
  flutter_riverpod: ^2.3.6
  form_builder_validators: ^8.4.0
  freezed_annotation: ^2.2.0
  go_router: ^6.0.9
  great_circle_distance_calculator: ^1.0.4
  hooks_riverpod: ^2.3.4
  http: ^0.13.5
  image_gallery_saver: ^1.7.1
  intl: ^0.17.0
  latlong2: ^0.8.1
  location: ^4.4.0
  riverpod: ^2.2.0
  rxdart: ^0.27.7
  share_plus: ^4.1.0
  sliver_tools: ^0.2.7
  tuple: ^2.0.1

dev_dependencies:
  build_runner: ^2.3.0
  build_verify: ^3.1.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  go_router_builder: ^1.1.1
  integration_test:
    sdk: flutter
  json_serializable: ^6.5.4
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
