name: listanything
description: A starter template for Flutter projects
version: 0.0.29+0000001
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analytics_repository:
    path: packages/analytics_repository
  another_xlider: ^3.0.2
  app_ui:
    path: packages/app_ui
  authentication_client:
    path: packages/authentication_client/authentication_client
  bloc: ^8.1.0
  bloc_concurrency: ^0.2.2
  cloud_firestore: ^4.9.2
  collection: ^1.17.2
  device_info_plus: ^9.0.3
  email_launcher:
    path: packages/email_launcher
  equatable: ^2.0.3
  firebase_analytics: ^10.4.5
  firebase_auth: ^4.10.0
  firebase_authentication_client:
    path: packages/authentication_client/firebase_authentication_client
  firebase_core: ^2.15.1
  firebase_crashlytics: ^3.3.5
  firebase_dynamic_links: ^5.3.5
  firebase_in_app_messaging: ^0.7.3+6
  firebase_messaging: ^14.6.7
  firebase_performance: ^0.9.2+6
  firebase_remote_config: ^4.2.6
  flow_builder: ^0.0.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_form_builder: ^9.1.1
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.1.0
  form_builder_validators: ^9.1.0
  form_inputs:
    path: packages/form_inputs
  formz: ^0.6.0
  freezed_annotation: ^2.4.1
  go_router: ^12.1.1
  google_fonts: ^4.0.0
  google_maps_flutter: ^2.5.0
  google_maps_flutter_web: ^0.5.4+2
  great_circle_distance_calculator: ^1.0.4
  http: ^0.13.6
  hydrated_bloc: ^9.1.2
  intl: ^0.18.0
  json_annotation: ^4.8.1
  latlong2: ^0.9.0
  logger: ^2.0.2+1
  meta: ^1.7.0
  path_provider: ^2.1.1
  persistent_storage:
    path: packages/storage/persistent_storage
  shared_preferences: ^2.2.1
  token_storage:
    path: packages/authentication_client/token_storage
  user_repository:
    path: packages/user_repository

dev_dependencies:
  bloc_test: ^9.0.0
  build_runner: ^2.4.6
  build_verify: ^3.1.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  go_router_builder: ^2.3.2
  json_serializable: ^6.7.1
  mockingjay: ^0.4.0
  mocktail: ^1.0.0
  test: ^1.24.1
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/


