name: listanything
description: List anything, sometimes with a map
version: 0.0.28+0000001
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  # sdk: ">=2.19.0 <3.0.0"

dependencies:
  another_xlider: ^3.0.1
  cloud_firestore: ^4.4.3
  collection: ^1.17.1
  device_info_plus: ^8.2.2
  firebase_analytics: ^10.3.0
  firebase_app_installations: ^0.2.3+4
  firebase_auth: ^4.7.0
  firebase_core: ^2.6.1
  firebase_core_web: ^2.2.1
  firebase_crashlytics: ^3.2.0
  firebase_in_app_messaging: ^0.7.3+4
  firebase_messaging: ^14.6.5
  firebase_performance: ^0.9.2+4
  firebase_remote_config: ^4.2.4
  firebase_ui_auth: ^1.6.0
  firebase_ui_oauth_google: ^1.2.5
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.0.0
  flutter_hooks: ^0.18.6
  flutter_localizations:
    sdk: flutter
  flutter_map: ^5.0.0
  flutter_riverpod: ^2.3.6
  form_builder_validators: ^9.0.0
  freezed_annotation: ^2.2.0
  go_router: ^9.0.3
  google_maps_flutter: ^2.1.8
  google_maps_flutter_web: ^0.5.1
  google_sign_in: ^6.1.4
  great_circle_distance_calculator: ^1.0.4
  hooks_riverpod: ^2.3.6
  http: ^1.1.0
  image_gallery_saver: ^2.0.3
  intl: ^0.18.0
  json_annotation: ^4.8.1
  latlong2: ^0.9.0
  location: ^5.0.0
  logger: ^1.3.0
  riverpod: ^2.2.0
  rxdart: ^0.27.7
  share_plus: ^4.1.0
  sliver_tools: ^0.2.7
  tuple: ^2.0.1

dev_dependencies:
  build_runner: ^2.4.4
  build_verify: ^3.1.0
  custom_lint: ^0.4.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  go_router_builder: ^2.2.1
  integration_test:
    sdk: flutter
  json_serializable: ^6.5.4
  mocktail: ^0.3.0
  riverpod_lint: ^1.3.2
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
