name: listanything
description: List anything, sometimes with a map
version: 0.0.1+0000001
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  build_runner: ^2.3.0
  build_verify: ^3.1.0
  device_info_plus: ^8.1.0
  firebase_auth: ^4.2.8
  firebase_core: ^2.6.1
  firebase_core_web: ^2.2.1
  firebase_ui_auth: ^1.1.13
  firebase_ui_oauth_google: ^1.0.21
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_hooks: ^0.18.6
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.1.1
  go_router: ^6.0.9
  go_router_builder: ^1.1.1
  intl: ^0.17.0
  riverpod: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
