name: core_models
description: A starting point for Dart libraries or applications.
version: 0.0.1
publish_to: none

resolution: workspace

environment:
  sdk: ^3.12.0

# Add regular dependencies here.
dependencies:
  freezed_annotation: ^3.1.0
  json_annotation: ^4.12.0

  anyhoo_core:
    git:
      url: https://github.com/Anyhoosolutions/flutter_platform_kit.git
      path: packages/anyhoo_core
      ref: dd36384a3fb30c7442795676d579d2a01773caf3
  anyhoo_logging:
    git:
      url: https://github.com/Anyhoosolutions/flutter_platform_kit.git
      path: packages/anyhoo_logging
      ref: dd36384a3fb30c7442795676d579d2a01773caf3
  anyhoo_models:
    git:
      url: https://github.com/Anyhoosolutions/flutter_platform_kit.git
      path: packages/anyhoo_models
      ref: dd36384a3fb30c7442795676d579d2a01773caf3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  build_runner: ^2.15.0
  freezed: ^3.2.5
  json_serializable: ^6.14.0
  test_cov_console: ^0.2.2
  analyzer: ^10.0.0
