name: Upload docs

on:
  push:
    branches:
      - main
  pull_request:

env:
  # Setting an environment variable with the value of a configuration variable
  UPLOAD_URL: ${{ vars.UPLOAD_URL }}

jobs:
  run-main:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: '3.5'

      - name: Cache Dart packages
        uses: actions/cache@v3
        with:
          path: |
            .pub-cache/bin
            .pub-cache/global_packages
            .pub-cache/hosted
            .dart_tool
            .packages
          key: ${{ runner.os }}-dart-${{ hashFiles('**/pubspec.yaml') }}

      - name: Run main deployment
        run: |
          cd scripts/console
          dart pub get --no-precompile
          echo $UPLOAD_URL
          dart bin/console.dart

  run-non-main:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: '3.5'

      - name: Cache Dart packages
        uses: actions/cache@v3
        with:
          path: |
            .pub-cache/bin
            .pub-cache/global_packages
            .pub-cache/hosted
            .dart_tool
            .packages
          key: ${{ runner.os }}-dart-${{ hashFiles('**/pubspec.yaml') }}

      - name: Run non-main deployment
        run: |
          cd scripts/console
          dart pub get --no-precompile
          export GIT_COMMIT_HASH=$(git rev-parse HEAD)
          echo $UPLOAD_URL
          dart bin/console.dart --commitHash=$GIT_COMMIT_HASH

      - name: Build PR docs link
        run: |
          echo "pr_docs_link=$(git rev-parse HEAD | head -c 7)" >> $GITHUB_ENV

      # - name: Comment PR
      #   uses: thollander/actions-comment-pull-request@v3
      #   with:
      #     message: |
      #       https://anywhostudios--anywhostudios-8eef2.us-central1.hosted.app/projects/${{ env.pr_docs_link }}
